# Dell XPS laptop performance profile.
[main]
summary=Dynamic performance profile for the Dell XPS
include=balanced

[cpu]
governor=powersave
energy_perf_bias=performance
energy_performance_preference=performance
boost=1

[acpi]
platform_profile=performance
