FROM fedora:44
RUN dnf install -y python3-pyside6 python3-jinja2 python3-pyyaml \
    ShellCheck pykickstart qt6-qtdeclarative-devel desktop-file-utils \
    && dnf clean all
ENV QT_QPA_PLATFORM=offscreen
WORKDIR /source
CMD ["python3", "image/tests"]
